
version: '3'

services:
  keycloak:
      command: start-dev
      image: quay.io/keycloak/keycloak:20.0.3
      volumes:
        - ./h2:/opt/keycloak/data/h2/
      ports:
      - "8081:8080"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin