version: '3'
services:
  sds-auth-server:
    image: "jboss/keycloak:10.0.2"
    container_name: sds-idp
    networks:
      - keycloak-network
    ports:
      - "8180:8080"
    volumes:
      - ./realms:/tmp/realms
      - ./.keycloak_sds:/opt/jboss/keycloak/standalone/data/
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # KEYCLOAK_IMPORT: /tmp/realms/sds_auth_realm.json
    extra_hosts:
      sds.idp.com: 172.23.0.1
      telstra.idp.com: 172.23.0.1
    networks:
      - keycloak-network

  telstra-auth-server:
    image: "jboss/keycloak:10.0.2"
    container_name: telstra-idp
    ports:
      - "8280:8080"
    volumes:
      - ./realms:/tmp/realms
      - ./.keycloak_telstra:/opt/jboss/keycloak/standalone/data/
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # KEYCLOAK_IMPORT: /tmp/realms/telstra_auth_realm.json
    extra_hosts:
      sds.idp.com: 172.23.0.1
      telstra.idp.com: 172.23.0.1
    networks:
      - keycloak-network
networks:
  keycloak-network:
    driver: bridge